name: Web CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Build web app
        run: pnpm -C apps/web-svelte build

      - name: Test (if present)
        run: pnpm -C apps/web-svelte test --if-present
